version: '3'


services:
  # The database service
  db:
    image: postgres:14.4
    # por cualquier cambio se va a actualizar
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: reclamosDB
    volumes:
      - ./postgres:/data

  # The backend service